config/routes.rb
Rails.application.routes.draw do
  # get 'locations/index'
  # get 'locations/show'
  # get 'locations/edit'
  # get 'locations/new'
  # get 'addresses/index'
  # get 'addresses/show'
  # get 'addresses/new'
  # get 'trips/index'
  # get 'trips/show'
  # get 'trips/new'
  # get 'trips/edit'
  devise_for :users
  root "trips#index"

  resources :trips do
    resources :locations 
  end
    
  resources :locations do
    resources :addresses
  end

  ## Todo add model resources later linking trips, locations, addresses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

#This is a test from Jon. 
# scott here

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :location
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :addresses
  belongs_to :trip
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :locations
end

app/models/user.rb
class User < ApplicationRecord
      has_many :trips
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_location
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  def index
    @addresses = @location.addresses
  end

  def show

  end

  def new
    @address = @location.addresses.new
    render :_form
  end

  def create
    @address = @location.addresses.new(address_params)
    if @address.save
      redirect_to location_addresses_path
    else
      render :new
    end
  end

  def edit
    render :_form
  end

  def update
    if @address.update(address_params)
      redirect_to location_address_path(@location)
    else
      render :_form
    end
  end

  def destroy
    @address.destroy
    redirect_to location_addresses_path(@location)
  end

  private

  def set_location
    @location = Location.find(params[:location_id])
  end

  def set_address
    @address = Address.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:street, :state, :city, :country, :region, :zip, :location_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :update, :edit, :destroy]
  before_action :set_trip
  
  def index
   @locations = Location.all
  end

  def show

  end

  def edit
  end

  def new
   @location = @trip.locations.new
   render partial: 'form'
  end
  def create 
    @location = @trip.locations.new(location_params)

    if @location.save
      redirect_to trip_locations_path(@trip)
    else 
      render :new
    end
  end 
  def update
    if @location.update(location_params)
      redirect_to locations_path
    else 
      render :edit
    end 
  end
  def destroy 
    @location.destroy 
    redirect_to locations_path
  end 
  private 

     def set_trip
    @trip = Trip.find(params[:trip_id])
    end

     def set_location
      @location = Location.find(params[:id])
    end 

    def location_params
      params.require(:location).permit(:loc_name)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  def index
    @trips = current_user.trips
  end

  def show
  end

  def new
    @trip = Trip.new
    render partial: 'form'
  end

  def edit
    @trip = current_user.trips.new(trip_params)
    if @trip.save
      redirect_to trips_path
    else
      render :new
    end
  end

  def create
    @trip = current_user.trips.new(trip_params)

    if @trip.save
      redirect_to trips_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @trip.update(trip_params)
      redirect_to trips_path
    else
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private

  def trip_params
    params.require(:trip).permit(:name)
  end

  def set_trip
    @trip = Trip.find(params[:id])
  end
end
  

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/_form.html.erb
<h1><%= @address.id ? 'Edit Address' : 'Create Address' %></h1>
<hr />
<%= form_for [@location, @address] do |f| %>
  <%= f.label :street %>
  <%= f.text_field :street, required: true, autofocus: true, placeholder: "Street Address" %>
  <%= f.label :city %>
  <%= f.text_field :city, required: true, placeholder: "City" %>
  <%= f.label :state %>
  <%= f.text_field :state, required: true, placeholder: "State" %>
  <%= f.label :region %>
  <%= f.text_field :region, required: true, placeholder: "Region" %>
  <%= f.label :country %>
  <%= f.text_field :country, required: true, placeholder: "Country" %>
  <%= f.label :zip %>
  <%= f.number_field :zip, required: true, placeholder: "Zip Code (numbers only)" %>
  <%= f.submit %>
<% end %>

app/views/addresses/index.html.erb
<h1>Addresses#index</h1>
<p>Find me in app/views/addresses/index.html.erb</p>
<% @addresses.each do |address| %>
  <%= address.street %>
  <%= address.city %>, <%= address.state %> <%= address.zip %>
  Country:<%= address.country %>
  Region:<% address.region %>
 <br>
  <%= link_to "Edit", edit_location_address_path(@location, address) %>
  <%= link_to "Delete", location_address_path(@location, address), method: :delete %>
  <br><br><br>
<% end %>
<br>
<%= link_to "Create New Address", new_location_address_path %>

app/views/addresses/new.html.erb
<h1>Addresses#new</h1>
<p>Find me in app/views/addresses/new.html.erb</p>

app/views/addresses/show.html.erb
<h1>Addresses#show</h1>
<p>Find me in app/views/addresses/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<h1><%= @location.id ? 'Edit Location' : 'Create Location' %></h1>
<hr />
<%= form_for [@trip, @location] do |f| %>
  <%= f.label 'Location Name' %>
  <%= f.text_field :loc_name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/locations/edit.html.erb
<h1>Locations#edit</h1>
<p>Find me in app/views/locations/edit.html.erb</p>

app/views/locations/index.html.erb
<h1>This is the Location</h1>
<%=link_to "Add location", new_location_path%>


<ul>
<% @locations.each do |location| %>
    <li> <%= link_to location.loc_name, [@trip,location]%></li>
<%end%>
</ul>

app/views/locations/new.html.erb
<h1>Locations#new</h1>
<p>Find me in app/views/locations/new.html.erb</p>

app/views/locations/show.html.erb
<h1>Here are your locations!</h1>
<h1><%= @location.loc_name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Locations', trip_locations_path(@location) %>
<br />
<%= link_to 'Edit a Location', edit_location_path(@location) %>
<br />
<%= link_to 'Delete a Location', @location, method: :delete %>
<%= link_to 'Addresses', location_addresses_path(:location_id) %>

app/views/trips/_form.html.erb
<h1><%= @trip.id ? 'Edit Trip' : 'Create Trip' %></h1>
<hr />
<%= form_for @trip do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/trips/edit.html.erb
<h1>Trips#edit</h1>
<p>Find me in app/views/trips/edit.html.erb</p>

app/views/trips/index.html.erb
<h1>View your trips!</h1>
<ul>
  <% @trips.each do |trip| %>
    <li><%= link_to trip.name, trip %></li>
  <% end %>
</ul>
<%= link_to 'Create a new trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>Add Trip</h1>
<%= form_for @trip do |f|%>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, placeholder: "First Name", autofocus: true %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/trips/show.html.erb
<h1>Here are your trips!</h1>
<h1><%= @trip.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'Add Location', new_trip_location_path(@trip) %>
<br />
<%= link_to 'View Locations', trip_locations_path(@trip) %>
<br />
<%= link_to 'Edit Trips', edit_trip_path(@trip) %>
<br />
<%= link_to 'Delete Trip', @trip, method: :delete %>